config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  #get 'home/index'
  get 'home/about'
  get 'home/lookup'
  post "home/lookup" => 'home/lookup'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: %i[ show edit update destroy ]
  before_action :correct_user, only: %i[ show edit update destroy]
  before_action :authenticate_user!

  # GET /cryptos or /cryptos.json
  def index
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'

    #@url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?CMC_PRO_API_KEY=e75d37d1-b7b2-4253-9f36-289eaff48122'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=e75d37d1-b7b2-4253-9f36-289eaff48122&start=1&limit=5000&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_crypto = JSON.parse(@response)
    @profit_loss = 0
  end

  # GET /cryptos/1 or /cryptos/1.json
  def show
    @cryptos = Crypto.all
    require 'net/http'
    require 'json'

    #@url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?CMC_PRO_API_KEY=e75d37d1-b7b2-4253-9f36-289eaff48122'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=e75d37d1-b7b2-4253-9f36-289eaff48122&start=1&limit=5000&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_crypto = JSON.parse(@response)
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos or /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: "Crypto was successfully created." }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1 or /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: "Crypto was successfully updated." }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1 or /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: "Crypto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @crypto = current_user.cryptos.find_by(id: params[:id])
    redirect_to cryptos_path, notice: "You are not authorized to preform this action." if @crypto.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    #@cryptos = Crypto.all
    require 'net/http'
    require 'json'

    #@url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?CMC_PRO_API_KEY=e75d37d1-b7b2-4253-9f36-289eaff48122'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=e75d37d1-b7b2-4253-9f36-289eaff48122&start=1&limit=5000&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
    @my_coins = ["BTC", "ETH", "XRP", "ADA", "BNB", "USDT", "SOL", "DOGE"]
    @coinlist = []
  end

  def lookup
    require 'net/http'
    require 'json'

    #@url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?CMC_PRO_API_KEY=e75d37d1-b7b2-4253-9f36-289eaff48122'
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=e75d37d1-b7b2-4253-9f36-289eaff48122&start=1&limit=5000&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coin = JSON.parse(@response)

    @symbol = params[:sym]

    #error handling on lookup form
    #changing the input text to uppercase to match on key value pair of JSON on API
    if @symbol
          @symbol = @symbol.upcase
    end

    #if entered an empty value
    if @symbol == ""
        @symbol = "Please Enter A Currency!"
    end
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto) do |form| %>
  <% if crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
        <% crypto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Show', @crypto %> |
<%= link_to 'Back', cryptos_path %>

app/views/cryptos/index.html.erb
<h1>My Cryptocurrency</h1>
<br/>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Current Price</th>
      <th>1hr %</th>
      <th>24hr %</th>
      <th>7d %</th>
      <th>Current Value</th>
      <th>Total Paid</th>
      <th>Profit / Loss</th>
      <th>Cost Paid Per</th>
      <th>Amount Owned</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
     <% if crypto.user_id == current_user.id %>
        <% if crypto.symbol %>
          <%  crypto.symbol = crypto.symbol.upcase %>
        <% end %>
        <tr>
        <% for x in @lookup_crypto['data'] %>
          <% if crypto.symbol == x['symbol'] %>
              <td><%= x['cmc_rank'] %></td>
              <td><%=link_to x['name'], crypto %>: <%= crypto.symbol %></td>
              <td>$<%= number_with_precision(x['quote']['USD']['price'], :precision => 5, :delimiter => ',') %></td>

              <td><%= number_to_percentage(x['quote']['USD']['percent_change_1h']) %></td>
              <td><%= number_to_percentage(x['quote']['USD']['percent_change_24h']) %></td>
              <td><%= number_to_percentage(x['quote']['USD']['percent_change_7d']) %></td>

              <td>$<%= number_with_precision(x['quote']['USD']['price'].to_d * crypto.amount_owned, :precision => 5, :delimiter => ',') %></td>
              <td><%= number_to_currency(crypto.cost_per * crypto.amount_owned) %></td>
              <td><%= number_to_currency((x['quote']['USD']['price'].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned), :precision => 5, :delimiter => ',') %></td>
              <% @profit_loss += (x['quote']['USD']['price'].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned) %>
          <% end %>
        <% end %>
          <td><%= number_to_currency(crypto.cost_per) %></td>
          <td><%= crypto.amount_owned %></td>
          <!-- <td><%= link_to 'Show', crypto %></td> -->
          <!-- <td><%= link_to 'Edit', edit_crypto_path(crypto) %></td> -->
          <!-- <td><%= link_to 'Destroy', crypto, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br/><br/>

<strong>My Profit / Loss: </strong> <%= number_to_currency(@profit_loss, :precision => 2, :delimiter => ',') %>

<br/><br/>

<%= link_to 'New Crypto', new_crypto_path %>

app/views/cryptos/new.html.erb
<h1>New Crypto</h1>

<%= render 'form', crypto: @crypto %>

<%= link_to 'Back', cryptos_path %>

app/views/cryptos/show.html.erb
<% for x in @show_crypto['data'] %>
  <% if @crypto.symbol.upcase == x['symbol'] %>
      <% crypto_name = x['name'] %>
      <% crypto_price = number_with_precision(x['quote']['USD']['price'], :precision => 5, :delimiter => ',') %>
      <% crypto_rank = x['cmc_rank'] %>
  <% end %>
<% end %>

<div class="card">
  <div class="card-header">
    <h3><%= crypto_name %></h3>
  </div>

  <div class="card-body">
    <h1><%= @crypto.symbol.upcase %></h1>

  <p>
    <strong>Current Price: </strong><%= number_to_currency(crypto_price) %>
  </p>

  <p>
    <strong>Rank: </strong><%= crypto_rank %>
  </p>

  <p>
    <strong>Cost per: </strong><%= number_to_currency(@crypto.cost_per) %>
  </p>

  <p>
    <strong>Amount owned: </strong><%= number_to_currency(@crypto.amount_owned) %>
  </p>
  </div>

  <div class="card-footer">
  <%= link_to 'Edit', edit_crypto_path(@crypto) %> |
  <%= link_to 'Delete', crypto_path(@crypto), method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Back', cryptos_path %>
  </div>
</div>

app/views/home/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <%= link_to "Crypto Portfolio", root_path, class: "navbar-brand" %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
             <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
             <li class="nav-item"><%= link_to "Lookup", home_lookup_path, class: "nav-link" %></li>
             <li class="nav-item"><%= link_to "About Us", home_about_path, class: "nav-link" %></li>
             
        <%# conditional navbar links %>
        <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "My Cryptos", cryptos_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Add Crypto", new_crypto_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
        <% else %>
            <li class="nav-item" ><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
            <li class="nav-item" data-bs-toggle="modal" data-bs-target="#exampleModal">LOGIN</li>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
        <% end %>
        </ul>

      </div> <!-- /.navbar-collapse -->
  </div> <!-- /.container-fluid -->
</nav>


<!-- Button trigger modal -->
<%# <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button> %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">User Login</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
        <div class="form-floating mb-3">
          <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" required="required">
          <label for="floatingInput">Email address</label>
        </div>
        <div class="form-floating">
          <input type="password" class="form-control" id="floatingPassword" placeholder="Password" required="required">
          <label for="floatingPassword">Password</label>
        </div><br/>
        <div class="d-grid gap-2"">
          <button type="submit" class="btn btn-primary">Login</button>
        </div><br/>
  
        <div class="form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Remember me</label>

          <a href="#" class="text-primary text-decoration-none float-end">Forgot Password?</a>
        </div>

      </div>

      <div class="modal-footer">
        <p class="text-muted">Not yet registered?</p>
        <p><a href="#" class="text-muted text-decoration-none">Sign Up here</a></p>
      </div>  
    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>Some information here</p>

app/views/home/index.html.erb
<% @coins %>

<% for x in @coins['data'] %>
    <% for coin in @my_coins %>
        <% if coin == x['symbol'] %>
            <% x['name'] %> <% x['quote']['USD']['price'] %><br/>
            <% @coinlist.push(x['quote']['USD']['price']) %>
        <% end %>
    <% end %>
<% end %>

<div class="row row-cols-3 row-cols-md-4 g-4">
  <div class="col">
    <div class="card"><br/>
      <%=image_tag("btc.png", size: "65x65", class: "mx-auto d-block", alt: "BITCOIN")%>
      <div class="card-body">
        <h5 class="card-title text-center">Bitcoin</h5>
        <p class="card-text text-center">BTC</p>
        <h6 class="card-title text-center"><%= number_to_currency(@coinlist.fetch(0))%></h6>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card"><br/>
      <%=image_tag("eth.png", size: "65x65", class: "mx-auto d-block", alt: "ETHEREUM")%>
      <div class="card-body">
        <h5 class="card-title text-center">Ethereum</h5>
        <p class="card-text text-center">ETH</p>
        <h6 class="card-title text-center"><%= number_to_currency(@coinlist.fetch(1))%></h6>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card"><br/>
      <%=image_tag("ada.png", size: "65x65", class: "mx-auto d-block", alt: "CARDANO")%>
      <div class="card-body">
        <h5 class="card-title text-center">Cardano</h5>
        <p class="card-text text-center">ADA</p>
        <h6 class="card-title text-center"><%= number_to_currency(@coinlist.fetch(2))%></h6>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card"><br/>
      <%=image_tag("bnb.png", size: "65x65", class: "mx-auto d-block", alt: "BINANCE")%>
      <div class="card-body">
        <h5 class="card-title text-center">Binance Coin</h5>
        <p class="card-text text-center">BNB</p>
        <h6 class="card-title text-center"><%= number_to_currency(@coinlist.fetch(3))%></h6>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card"><br/>
      <%=image_tag("usdt.png", size: "65x65", class: "mx-auto d-block", alt: "TETHER")%>
      <div class="card-body">
        <h5 class="card-title text-center">Tether</h5>
        <p class="card-text text-center">USDT</p>
        <h6 class="card-title text-center"><%= number_to_currency(@coinlist.fetch(4))%></h6>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card"><br/>
      <%=image_tag("xrp.png", size: "65x65", class: "mx-auto d-block", alt: "RIPPLE")%>
      <div class="card-body">
        <h5 class="card-title text-center">Ripple</h5>
        <p class="card-text text-center">XRP</p>
        <h6 class="card-title text-center"><%= number_to_currency(@coinlist.fetch(5))%></h6>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card"><br/>
      <%=image_tag("sol.png", size: "65x65", class: "mx-auto d-block", alt: "SOLANA")%>
      <div class="card-body">
        <h5 class="card-title text-center">Solana</h5>
        <p class="card-text text-center">SOL</p>
        <h6 class="card-title text-center"><%= number_to_currency(@coinlist.fetch(6))%></h6>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card"><br/>
      <%=image_tag("doge.png", size: "65x65", class: "mx-auto d-block", alt: "DOGECOIN")%>
      <div class="card-body">
        <h5 class="card-title text-center">Dogecoin</h5>
        <p class="card-text text-center">DOGE</p>
        <h6 class="card-title text-center"><%= number_to_currency(@coinlist.fetch(7))%></h6>
      </div>
    </div>
  </div>
</div>

<br/><br/>

app/views/home/lookup.html.erb
<h3>Cryptocurrency Lookup</h3>
<br/>

<%= form_tag home_lookup_path, :method => 'POST' do %>
    <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', size: 50 %>
    <%= submit_tag 'Lookup Stock Quote' %>
<% end %>

<br/><br/>

<%# @symbol %>

<%# error handling %>
<%# execute only when @symbol has value %>
<% if @symbol %>
    <% for x in @lookup_coin['data'] %>
        <% if @symbol == x['symbol'] %>
            <%= x['name'] %>: $<%= x['quote']['USD']['price'] %><br/>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptocurrency Portfolio App</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  <%= render 'home/navbar' %>
  
  <div class="container">
    <%= render 'home/flash' %>
    <%= yield %>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
  </body>
</html>